//
// Address.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import CoreLocation

public struct AddressModel: Codable {

    /** Unit, suite, or PO Box */
    public var addressLine2: String?
    public var addressType: String?
    /** City name */
    public var city: String?
    /** Country code (ISO 3166 2-Alpha) */
    public var country: String?
    /** Latitude of address */
    public var latitude: Double?
    /** Longitude of address */
    public var longitude: Double?
    /** Postal or zip code */
    public var postalCode: String?
    /** State or province name or short form */
    public var state: String?
    /** Street address */
    public var streetAddress: String?

    public init() {
        // This is a required method for initialisation.
    }

    public init(addr: AddressModel) {
        self.addressLine2   = addr.addressLine2
        self.addressType    = addr.addressType
        self.city = addr.city
        self.country = addr.country
        self.latitude = addr.latitude
        self.longitude = addr.longitude
        self.postalCode = addr.postalCode
        self.state = addr.state
        self.streetAddress = addr.streetAddress
    }

    // Handle optionals as needed
    public init(with placemark: CLPlacemark) {

        self.streetAddress = "\(placemark.name ?? "") \(placemark.thoroughfare ?? "") \(placemark.subThoroughfare ?? "")"
        self.addressType = "mailing"
        self.city = placemark.locality ?? ""
        self.postalCode = placemark.postalCode ?? ""
        self.state = placemark.administrativeArea ?? ""
        self.country = placemark.country ?? ""
        self.latitude = placemark.location?.coordinate.latitude
        self.longitude = placemark.location?.coordinate.longitude
    }

    func isEquals(addr: AddressModel!) -> Bool {
        if addr == nil {
            return false
        }
        let line1           = (self.streetAddress   == addr.streetAddress)
        let line2           = (self.addressLine2    == addr.addressLine2)
        let cityCheck       = (self.city            == addr.city)
        let countryCheck    = (self.country         == addr.country)
        let postalCodeCheck = (self.postalCode      == addr.postalCode)
        let stateCheck      = (self.state           == addr.state)

        return line1 && line2 && cityCheck && countryCheck && postalCodeCheck && stateCheck
    }

    func addressString() -> String {
        return "\(streetAddress ?? ""), \(city ?? ""), \(country ?? "") \(postalCode ?? "")"
    }
}

// MARK: - Address
public struct Address: Codable {
    public var addressType: String?
    public var line1: String?
    public var line2: String?
    public var city: String?
    public var state: String?
    public var country: String?
    public var postalCode: String?

    public init() {
        // This is a required method.
    }

    func addressString() -> String {
        var addrString = "\(line1 ?? ""), \(city ?? ""), \(state ?? "")"

        if addrString.hasPrefix(",") &&  addrString.count > 1 {
            addrString = addrString.substring(from: 1)
        }
        let checkEmptyString = addrString.replacingOccurrences(of: ",", with: "", options:
                                                                .literal, range: nil)

        return checkEmptyString.trim.count > 0 ? addrString : checkEmptyString.trim
    }

    func addressStringWithPostalCode() -> String {
        var addrString = "\(line1 ?? ""), \(line2 ?? ""), \(city ?? ""), \(state ?? "") \(postalCode ?? "")"

        if addrString.hasPrefix(",") &&  addrString.count > 1 {
            addrString = addrString.substring(from: 1)
        }

        addrString = addrString.replacingOccurrences(of: ", ,", with: ",", options: .literal, range: nil)

        let checkEmptyString = addrString.replacingOccurrences(of: ",", with: "", options:
                                                                .literal, range: nil)

        return checkEmptyString.trim.count > 0 ? addrString : checkEmptyString.trim
    }

    public init(with placemark: CLPlacemark) {

        self.line1 = "\(placemark.name ?? "") \(placemark.thoroughfare ?? "") \(placemark.subThoroughfare ?? "")"
        self.addressType = "mailing"
        self.city = placemark.locality ?? ""
        self.postalCode = placemark.postalCode ?? ""
        self.state = placemark.administrativeArea ?? ""
        self.country = placemark.country ?? ""
    }
}
